### PR TITLE
move the repo_key configuration to a variable

### PR DESCRIPTION
**Pull request by Meecr0b**
in order to make the repository gpg key configurable, i implemented a repo_key variable.

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Meecr0b** [comment]
ping

**Comment by dlerch-tpgroup** [comment]
is this project dead?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @Meecr0b,

Thank you for helping improving the quality of this role.

After updating your branch from master branch, it is failing on all Ubuntu 14.04 tests (https://devops-ci.elastic.co/job/elastic+ansible-beats+pull-request/22/) with the following error:

```
       TASK [ansible-beats : Debian - Add Beats repository key] ***********************
       [DEPRECATION WARNING]: evaluating use_repository as a bare variable, this 
       behaviour will go away and you might need to add |bool to the expression in the
        future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature 
       will be removed in version 2.12. Deprecation warnings can be disabled by 
       setting deprecation_warnings=False in ansible.cfg.
       fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for packages.elastic.co:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname 'packages.elastic.co' doesn't match 'e.sni.fastly.net'."}
```

**Comment by jmlrt** [comment]
Installing APT packages `python-urllib3`, `python-openssl`, `python-pyasn1`, `python-pip` and PIP package `ndg-httpsclient` should solved issue (https://github.com/ansible/ansible/issues/9966).

```
--- a/tasks/beats-debian.yml
+++ b/tasks/beats-debian.yml
@@ -6,6 +6,19 @@
   register: beat_install
   notify: restart beat

+- name: Debian - ensure python-urllib3, python-openssl, python-pyasn1 & python-pip are installed
+  apt:
+    name: python-urllib3,python-openssl,python-pyasn1,python-pip
+    state: present
+  when: use_repository and ansible_distribution_release == "trusty"
+
+- name: Debian - ensure ndg-httpsclient pip is installed
+  pip:
+    name: ndg-httpsclient
+    state: present
+  when: use_repository and ansible_distribution_release == "trusty"
+
```

**Comment by elasticcla** [comment]
Hi @Meecr0b, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/ansible-beats/pull/10.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by nyetwurk** [comment]
This is problematic because it may overlap with other roles that use the variable "repo_key" that also include this role.

**Comment by jmlrt** [comment]
Hi @nyetwurk,
Thanks for reporting this problem.
Yes, `repo_url` and `repo_key` variable name are maybe too generic and should be prefixed by `elastic_`.
Can you create a new issue for that (or even better a PR to fix it)?

**Comment by nyetwurk** [comment]
Already have a simple diff, will open a bug/pr time permitting..

**Pull request merged**
