### PR TITLE
Support OSS versions of beats

### PR DESCRIPTION
**Pull request by watsonian**
This adds a new default variable called `use_oss` that defaults to false. If you set it to `true`, then the OSS package repositories are used. It also bumps the default beats version from `7.0.0` to `7.1.1`.

### CODE REVIEW

**Comment by watsonian** [comment]
@jmlrt Any chance of getting some eyes on this? The CLA is submitted now, so we should be good on that front.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by watsonian** [comment]
@jmlrt Pushed up the changes (less the test) that you mentioned. Is that more or less what you were after? I will say, it does seem very odd to have the config setting you disable to install the OSS version be called `beats_enable_xpack`. If I were looking for a setting to swap to the OSS version, that is definitely not the first thing I'd look for.

As for the tests, is what I'm looking for here essentially something like this:

```
test
└── integration
    ├── oss
    │   └── serverspec
    │       └── default_spec.rb
    └── oss.yml
```

with `oss.yml` setting `beats_enable_xpack` to `false` and then some additional tests in `default_spec.rb` to check that the oss version was actually installed?

**Comment by jmlrt** [comment]
Hi @watsonian sorry for the late answer.

I agree with you that `beats_enable_xpack` is not the more intuitive name but I'd like to keep consistency with equivalent variable name in [elastic/ansible-elasticsearch](https://github.com/elastic/ansible-elasticsearch) role. Maybe we'll rename both variables in both ansible roles later.

>As for the tests, is what I'm looking for here essentially something like this:
```
test
└── integration
    ├── oss
    │   └── serverspec
    │       └── default_spec.rb
   └── oss.yml
```
>with oss.yml setting beats_enable_xpack to false and then some additional tests in default_spec.rb to check that the oss version was actually installed?

As for the test, it is exactly that.

**Comment by nimmortal** [comment]
Hello guys, any progress on that?

**Comment by jmlrt** [comment]
Implemented in #61

**Pull request closed without merging**
