### PR TITLE
beat config improvements

### PR DESCRIPTION
**Pull request by MartinVerges**
In order to offer additional configuration possibilities which we use internally, I have extended the template accordingly by the variable `bead_additional_conf`. So it is possible to create any beat configuration.

Furthermore our lint test showed some bugs which will be fixed with the second commit.

I would be happy about a merge!

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @MartinVerges,
Any beat configuration can be added via `{{ beat_conf }}` ansible variable.
Can you provide an example where it would make sense to use `{{ beat_additional_conf }}` variable instead of `{{ beat_conf }}`?

**Comment by MartinVerges** [comment]
hi, for example to configure `filebeat.modules` or `setup.kibana` or any of all the other options within the reference configuration of the beats.

**Comment by jmlrt** [comment]
You can already configure `filebeat.modules`, `setup.kibana` or any configuration mentioned in [filebeat-reference-yml](https://www.elastic.co/guide/en/beats/filebeat/7.4/filebeat-reference-yml.html) via `beat_conf` variable.

**Comment by MartinVerges** [comment]
hmm ok, good to know ;)
then the rest of the changes are just fixes for ansible-lint and yamllint.

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
