### PR TITLE
install filebeat modules and run filebeat setup

### PR DESCRIPTION
**Pull request by sdarwin**
Installs filebeat modules.   Let me know what you think.

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by felixb** [comment]
any updates on this PR?

**Comment by sdarwin** [comment]
Hi @felixb,

> any updates on this PR?

This was written about a year ago. At that time, I did testing and code review. It all appeared to be correct and functional. You might considered merging into your own local repo.

@jmlrt has proposed the similarity between metricbeat, filebeat, packetbeat, and so the code should somehow be more unified.

When making that decision, you have to weigh ease-of-use, simplicity, code maintainability, optimization. 
In the design here, there is a separate variable "filebeat_modules", a separate file "tasks/filebeat.yml", etc.. and the idea was that for other beats you'd plug them in with a similar method. A new variable "metricbeat_modules", a new file "tasks/metricbeat.yml". Each beat is clearly defined. This may result in some code duplication, but not a huge amount. In exchange for this duplication, you get a simple file layout, and you can easily customize each beat, and easily see what's happening in this ansible module.  The end-user is able to understand it, without knowing about all the different beats. They can focus on just one at a time.

**Comment by felixb** [comment]
Alright. I configured modules with current version without `modules.d` like this:

```
 beat_conf:
   filebeat.modules:
     - module: system
       syslog:
         enabled: true
       auth:
         enabled: true
```

**Pull request closed without merging**
