### PR TITLE
Rename the handlers

### PR DESCRIPTION
**Pull request by ktibi**
Closes : #47

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @ktibi, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/ansible-beats/pull/51.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ktibi** [comment]
@jmlrt Hi, can you approve CI ?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @ktibi,
The `{{ beat }}` variable in handler's name was added in https://github.com/elastic/ansible-beats/pull/34 because of an issue when running more than one role at once where only the one for the last beat role run was notified.
We'll need to do more test to ensure that we won't introduce regression here.

**Comment by ktibi** [comment]
@jmlrt Ok I see why need this feature. But right now, nothing works with ansible :/

**Comment by jmlrt** [comment]
@ktibi,

After some tests, I can confirm that your PR is breaking fix from #34 (only last `{{ beat }}` is restarted by handler when people deploy more than one Beat product like in [multi test](https://github.com/elastic/ansible-beats/blob/master/test/integration/multi.yml#L5-L6)).

This is tricky!

### first solution

Regarding https://github.com/ansible/ansible/issues/48466#issuecomment-437985126, I think that `{{ beat }}` shoud never be set as `host_var` or `group_var` in this Ansible role and you should.

 I guess the "Ansible way" to do that would be to have some `install_filebeat=true`, `install_metricbeat=false`variables in `host_var` or `groups_var`, then to use `include_role` with `when` conditionals in your playbook.

Example:
```
  hosts: all
  tasks:
    - include_role:
        name: "ansible-beats"
      vars:
        beat: "filebeat"
        beat_conf: {"filebeat": {"inputs":[{"paths":["/var/log/*.log"],"type":"log"}]} }
      when: install_filebeat==true
    - include_role:
        name: "ansible-beats"
      vars:
        beat: "metricbeat"
        beat_conf: { "metricbeat.modules": [{"module": "system", "metricsets": ["cpu", "filesystem", "network", "process"], "enabled": true, "period": "10s", "processes":[".*"], "cpu_ticks": false } ] }
      when: install_metricbeat==true
```

I tested it sucessfully in Kitchen tests with playbook variables but not with `host_var` ou `groups_var`, so that would need a real test to validate.

### second solution

Another option to make your PR works would be to set a fact based on `{{ beat }}` variable at the begining of the role (facts are not affected by https://github.com/ansible/ansible/issues/48466#issuecomment-437985126), then to flush the handlers at the end of the role (so that the good Beat is always restarted by handler before the fact is overrided in a new instance of the role for another Beat product).

**Comment by seanpringle** [comment]
I filed #47 

+1 for @jmlrt 's second solution, if it's the only way to allow use of a `beat` host or group var. The first solution doesn't follow the principle of least astonishment.

**Comment by ktibi** [comment]
@jmlrt Hi, I added your solution in my PR.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Thanks for the PR @ktibi 👍

**Pull request merged**
