### PR TITLE
restart beat daemon when a change was made in conf

### PR DESCRIPTION
**Pull request by Bikoumba**

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @Bikoumba,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by jmlrt** [comment]
related to https://github.com/elastic/ansible-beats/issues/5

**Comment by jmlrt** [comment]
Hi @Bikoumba, I think that https://github.com/elastic/ansible-beats/commit/dff01ce666b9715d3bce90b593a91c812a02ca6b should resolve your issue in a different way.

**Pull request closed without merging**
