### PR TITLE
add task to create directory for default policies

### PR DESCRIPTION
**Pull request by astik**
Follow up for #37

### CODE REVIEW

**Comment by astik** [comment]
current status : WIP

it needs more polishing. PR has been opened in order to share it with ansible-beat's team.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by astik** [comment]
Branch has been rebased on latest master.
Also, configuration is simplified, 2 settings to set up:

- beat_conf.setup.ilm.policy_file: default policy destination
- default_ilm_policy: default policy source (which JSON to copy)

Finally, i added some documentation.

It would be easier to use if there was only one settings to define, but that would introduce some hidden magic from the user. In its current form the role is more explicit.

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
