### PR TITLE
Make sure the right beat service gets restarted

### PR DESCRIPTION
**Pull request by nyetwurk**
When running more than one role at once, make sure all of the right notifies
get triggered, not just the one for the last beat role run.

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @nyetwurk,
Thanks for this PR.

Every "debian-based" tests are failing => [elastic+ansible-beats+pull-request/10](https://devops-ci.elastic.co/job/elastic+ansible-beats+pull-request/10).
It seems that you forgot to rename `notify` statement in [beats-debian.yml](https://github.com/Blockdaemon/ansible-beats/blob/nyet-fix-restart-PR1/tasks/beats-debian.yml#L7).
Can you fix that?

**Comment by nyetwurk** [comment]
> 
> 
> Hi @nyetwurk,
> Thanks for this PR.
> 
> Every "debian-based" tests are failing => [elastic+ansible-beats+pull-request/10](https://devops-ci.elastic.co/job/elastic+ansible-beats+pull-request/10).
> It seems that you forgot to rename `notify` statement in [beats-debian.yml](https://github.com/Blockdaemon/ansible-beats/blob/nyet-fix-restart-PR1/tasks/beats-debian.yml#L7).
> Can you fix that?

Hopefully fixed. Sorry about the oversight :)

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by nyetwurk** [comment]
Can someone please approve so I can keep my downstream clean :) thx

**Comment by jmlrt** [comment]
Jenkins test this please

**Comment by nyetwurk** [comment]
@jmlrt agreed on the `Starts beats service` handler as well. I will add it time permitting. Unfortunately I don't have CentosOS to test on, but do have Ubuntu/Debian/MacOS and all three of those seem fine.

**Comment by nyetwurk** [comment]
@jmlrt I think there is something wrong with the tests. It doesn't seem as if the handler isn't working, it seems as though none of the tasks that `notify` are being set as `changed: true`

**Comment by jmlrt** [comment]
FYI you can run automated test locally on all supported OS with our [KitchenCI](https://kitchen.ci/) setup assuming you have ruby and docker installed.

For this PR, you would need to run `make converge PATTERN=multi-centos-7` to test a deployment with filebeat and metricbeat on centos (playbook [test/integration/multi.yml](https://github.com/elastic/ansible-beats/blob/master/test/integration/multi.yml)). 

More details on the testing setup [here](https://github.com/elastic/ansible-beats/blob/master/README.md#testing).

**Comment by jmlrt** [comment]
> @jmlrt I think there is something wrong with the tests. It doesn't seem as if the handler isn't working, it seems as though none of the tasks that `notify` are being set as `changed: true`

The `restart {{ beat }}` handler is executed only when beat wasn't started by [`Start beats service`](https://github.com/Blockdaemon/ansible-beats/blob/nyet-fix-restart-PR1/tasks/beats.yml#L17) as you can see in the [`not beats_started.changed`](https://github.com/elastic/ansible-beats/blob/master/handlers/main.yml#L6) condition.

This way beat doesn't need to be restarted by handler during first ansible role deployment because it is already started by `Start {{ beat }} service` with up to date configuration. 

But if you change beats config and run the ansible role another time with beats already started, `Start {{ beat }} service` task will be in `ok` status (`beats_started.changed == false`) so the restart handler will restart beats to ensure new config is loaded.

**Comment by jmlrt** [comment]
Jenkins test this please

**Comment by nyetwurk** [comment]
Does that mean we need separate beats_not_changed for each kind of beat like we did for the handler (e.g. {{ beat }}_not_changed or {{beat}}.not_changed) since if you run two instances of the role from the same parent, the last one wins?

**Comment by jmlrt** [comment]
Yes we may need it, also I'm not sure.
I'm in holiday next week so I won't be able to test it.
Feel free to do some test if you have time for it or I'll take some time for that the week after.

**Comment by jmlrt** [comment]
@nyetwurk 
I finally found the time to do a few tests.

I can confirm you that we don't need separated `not beats_started.changed` conditions.

When testing it with `make converge multi-centos-7`:

- If I change only the configuration of filebeat (first instance in the role) and replay the role => only filebeat is restarted
- If I change only the configuration of metricbeat (second instance in the role) and replay the role => only metricbeat is restarted
- If I change only the configuration of both filebeat and metricbeat and replay the role => the two beats are restarted.

**Pull request merged**
